-- Artículo 4 (borrador) · ¿Cuánto vale mi apartamento en Bogotá?
delete from public.articulos_blog where slug = 'cuanto-vale-mi-apartamento-en-bogota' and estado = 'borrador';
insert into public.articulos_blog
  (titulo, slug, categoria, extracto, contenido, imagen_url, tiempo_lectura, estado, autor_id, autor_nombre, published_at)
values (
  '¿Cuánto vale mi apartamento en Bogotá? Guía para saberlo con datos, no con el precio del vecino',
  'cuanto-vale-mi-apartamento-en-bogota',
  'Mercado',
  'Avalúo catastral, comercial y precio de mercado no son lo mismo. Cómo se calcula de verdad el valor de un apartamento en Bogotá, qué lo mueve según la evidencia, cuánto se está pidiendo hoy por localidad y cuánto te queda neto después de vender.',
  $art$<!--lomaz
{
 "titulo_seo": "¿Cuánto vale mi apartamento en Bogotá? Guía con datos (2026)",
 "tema": "cómo saber cuánto vale un apartamento en Bogotá",
 "portada": false,
 "autor_bio": "Correduría independiente de vivienda y locales comerciales en Bogotá, fundada por Salomón Mazabell Torres Barrera.",
 "indice": [
  "La pregunta que casi todos responden mal",
  "Tres «valores» que no son el mismo",
  "Cómo se calcula de verdad",
  "Lo que mueve el precio, con evidencia",
  "Cuánto se está pidiendo hoy",
  "Precio de publicación y precio de cierre",
  "El atajo del arriendo",
  "Antes de publicar",
  "Cuánto te queda",
  "Preguntas frecuentes"
 ]
}
-->
<p>Tu vecino pide 520 millones por un apartamento «igual al tuyo». Un portal te dice que el metro cuadrado de tu localidad vale 7 millones. El avalúo catastral que llegó con el predial dice 310. Y el agente que te visitó la semana pasada soltó una cifra sin abrir el computador. Cuatro números, ninguna explicación. Esta guía existe para que, cuando alguien te diga cuánto vale tu apartamento, sepas qué preguntarle.</p>
<p>No vamos a darte una cifra: no existe una que sirva para todos. Vamos a darte algo más útil, el método con el que se llega a ella, los datos públicos que puedes revisar tú mismo y las trampas en las que cae la mayoría de los propietarios de Bogotá antes de publicar.</p>

<h2>1. La pregunta que casi todos responden mal</h2>
<p>En Bogotá la vivienda se encareció un <strong>7,09 % anual</strong> en el primer trimestre de 2026, la mayor alza en cinco trimestres según el Índice de Precios de la Propiedad Residencial del DANE, que mezcla vivienda nueva y usada. En el mismo periodo, las compraventas residenciales registradas en la ciudad <strong>cayeron 20,2 %</strong>: de 77.539 a 61.850 (<a href="https://www.portafolio.co/mis-finanzas/vivienda/la-vivienda-esta-un-7-09-mas-cara-en-bogota-su-mayor-alza-en-cinco-trimestres-pese-a-la-baja-de-tasas-del-banrep-496289" title="Portafolio, 17 de junio de 2026, con datos del DANE (IPPR) y de la Superintendencia de Notariado y Registro">Portafolio, con datos del DANE</a>).</p>
<p>Lee esas dos cifras juntas: los precios suben y se firman menos escrituras. Es la fotografía de un mercado donde muchos propietarios piden más y menos compradores pueden pagar. En septiembre de 2026 la tasa promedio de los créditos de vivienda estaba en <strong>14,71 % efectivo anual</strong> (<a href="https://www.elpais.com.co/economia/credito-de-vivienda-en-colombia-estos-son-los-bancos-con-las-tasas-mas-bajas-en-septiembre-de-2026-1103.html" title="El País, septiembre de 2026, con datos de la Superintendencia Financiera">Superintendencia Financiera, vía El País</a>) y el Banco de la República acababa de subir su tasa de intervención a <strong>12,25 %</strong> (<a href="https://www.elpais.com.co/economia/banco-de-la-republica-aumenta-su-tasa-de-interes-quedo-en-1225-3047.html" title="El País, 30 de septiembre de 2026">decisión del 30 de septiembre de 2026</a>). Con esas tasas, cada millón de más en el precio se traduce en una cuota que algún comprador deja de poder asumir.</p>
<p>Por eso «cuánto vale mi apartamento» no se responde mirando lo que piden los demás. Se responde mirando lo que se <em>firma</em>, y entendiendo qué hace que dos apartamentos del mismo edificio no valgan lo mismo.</p>

<h2>2. Tres «valores» que no son el mismo</h2>
<p>Buena parte de la confusión viene de que en Colombia conviven tres números con nombre parecido y uso distinto.</p>
<table>
<thead><tr><th>Número</th><th>Quién lo fija</th><th>Para qué sirve</th><th>Qué relación tiene con lo que te pagarán</th></tr></thead>
<tbody>
<tr><td><strong>Avalúo catastral</strong></td><td>La Unidad Administrativa Especial de Catastro Distrital (UAECD)</td><td>Calcular el impuesto predial y otras obligaciones fiscales</td><td>Por norma no puede ser inferior al 60 % del valor comercial ni superarlo. En la práctica suele estar bastante por debajo.</td></tr>
<tr><td><strong>Avalúo comercial</strong></td><td>Un avaluador inscrito en el Registro Abierto de Avaluadores (RAA)</td><td>Créditos hipotecarios, sucesiones, procesos judiciales, decisiones con efecto legal</td><td>Es la estimación formal del «precio más probable». Tiene valor probatorio; cuesta dinero y tarda días.</td></tr>
<tr><td><strong>Estudio de mercado o ACM</strong></td><td>Una inmobiliaria o un asesor</td><td>Definir el precio de salida y la estrategia de venta</td><td>No es un avalúo en el sentido legal. Su calidad depende por completo de los comparables que use y de cómo los ajuste.</td></tr>
</tbody>
</table>
<p>El <strong>avalúo catastral</strong> de Bogotá para 2026 cubre 2.965.917 predios y suma 945 billones de pesos, un 2,9 % más que en 2025 (<a href="https://bogota.gov.co/mi-ciudad/hacienda/bogota-alcanza-945-billones-en-valor-catastral-y-crece-29-en-2026" title="Alcaldía de Bogotá, 21 de enero de 2026: resultados del censo inmobiliario 2026">Alcaldía de Bogotá, enero de 2026</a>). Es un dato masivo, calculado por zonas y modelos, y por eso no captura si tu apartamento tiene vista o si el edificio cambió el ascensor. La regla de que no puede ser inferior al 60 % del valor comercial ni superarlo está en el artículo 2.2.2.1.1 del Decreto 1170 de 2015, modificado por el Decreto 148 de 2020, y Catastro Bogotá la repite en sus preguntas frecuentes (<a href="https://www.catastrobogota.gov.co/pregunta/que-es-el-avaluo-catastral" title="Catastro Bogotá: ¿qué es el avalúo catastral?">Catastro Bogotá</a>). Traducción: si tu avalúo catastral es de 310 millones, el valor comercial puede estar entre 310 y 517 millones. Un rango enorme, inútil para fijar precio.</p>
<p>El <strong>avalúo comercial</strong> lo define el Decreto 1420 de 1998 como «el precio más probable por el cual éste se transaría en un mercado donde el comprador y el vendedor actuarían libremente, con el conocimiento de las condiciones físicas y jurídicas que afectan el bien» (<a href="https://www.ani.gov.co/sites/default/files/decreto_1420_de_1998_tema_avaluos.pdf" title="Decreto 1420 de 1998, artículo 2: definición de valor comercial">artículo 2</a>). Solo puede firmarlo un avaluador inscrito en el RAA, según la Ley 1673 de 2013 (<a href="http://www.secretariasenado.gov.co/senado/basedoc/ley_1673_2013.html" title="Ley 1673 de 2013, artículos 3 y 6: definición de avaluador y Registro Abierto de Avaluadores">artículos 3 y 6</a>); puedes verificar el certificado de cualquier avaluador en <a href="https://www.raa.org.co/" title="Registro Abierto de Avaluadores">raa.org.co</a>. Si alguien te entrega un «avalúo» sin número de RAA, es un estudio de mercado con otro nombre.</p>
<p>El <strong>estudio de mercado</strong> (en el sector se le llama ACM, análisis comparativo de mercado) es lo que hace una inmobiliaria seria antes de aceptar un inmueble. No tiene efectos legales, pero es el que de verdad decide si vendes en tres meses o en un año. Y aquí está el punto: un buen ACM usa el mismo método que el avalúo comercial. Uno malo usa los avisos del vecino.</p>
<aside class="nota"><p>Si un banco va a financiar a tu comprador, ese banco pedirá su propio avalúo comercial. Si tu precio de venta queda muy por encima de ese avalúo, el crédito se aprueba por menos y la diferencia la tiene que poner el comprador de su bolsillo. Muchas ventas se caen exactamente ahí.</p></aside>

<h2>3. Cómo se calcula de verdad</h2>
<p>El Decreto 1420 de 1998 reconoce cuatro métodos de valuación: comparación o de mercado, renta o capitalización por ingresos, costo de reposición y residual (<a href="https://www.ani.gov.co/sites/default/files/decreto_1420_de_1998_tema_avaluos.pdf" title="Decreto 1420 de 1998, artículo 25: métodos de valuación">artículo 25</a>). Para un apartamento usado, el que manda es el primero. La Resolución 620 de 2008 del IGAC lo define como la técnica que «busca establecer el valor comercial del bien» a partir de ofertas o transacciones recientes de bienes comparables (<a href="https://www.alcaldiabogota.gov.co/sisjur/normas/Norma1.jsp?i=36158" title="Resolución 620 de 2008 del IGAC, artículo 1: método de comparación o de mercado">artículo 1</a>).</p>
<p>En la práctica, el método tiene cinco pasos:</p>
<ol>
<li><strong>Reunir comparables.</strong> Apartamentos parecidos, en la misma zona, vendidos o en oferta en los últimos meses. La misma resolución fija mínimos de muestra para algunos casos (<a href="https://www.alcaldiabogota.gov.co/sisjur/normas/Norma1.jsp?i=36158" title="Resolución 620 de 2008 del IGAC, artículo 20: tamaño mínimo de la muestra">artículo 20</a>); en un ACM profesional se trabaja con entre tres y diez.</li>
<li><strong>Distinguir cierres de avisos.</strong> Un aviso es un deseo; una escritura es un hecho. Los cierres pesan más. Para encontrarlos hay que preguntar en el edificio, revisar certificados de tradición de ventas recientes o apoyarse en bases de datos privadas.</li>
<li><strong>Homogeneizar.</strong> Ningún comparable es idéntico. Se ajusta cada uno por área, antigüedad, acabados, piso, parqueadero y ubicación hasta llevarlo a las condiciones del tuyo. La Resolución 620 exige que los ajustes sean explícitos y razonables (<a href="https://www.alcaldiabogota.gov.co/sisjur/normas/Norma1.jsp?i=36158" title="Resolución 620 de 2008 del IGAC, artículos 11 y 12: dispersión de la muestra y ajustes">artículos 11 y 12</a>).</li>
<li><strong>Revisar la dispersión.</strong> Si los valores ajustados por metro cuadrado se parecen entre sí, la muestra sirve. El IGAC adopta la media como valor más probable cuando el coeficiente de variación está dentro del 7,5 % (<a href="https://www.alcaldiabogota.gov.co/sisjur/normas/Norma1.jsp?i=36158" title="Resolución 620 de 2008 del IGAC, artículo 11: coeficiente de variación">artículo 11</a>). Si uno se dispara, se descarta.</li>
<li><strong>Convertir el valor en estrategia.</strong> El resultado no es un número sino un rango: un mínimo por debajo del cual no conviene bajar, un valor comercial probable y un máximo defendible. El precio de salida se elige dentro de ese rango según la urgencia del propietario y la competencia del momento.</li>
</ol>
<p>Un ejemplo ilustrativo, con cifras inventadas para mostrar el mecanismo. Tu apartamento tiene 80 m², 15 años, piso 7 con vista exterior y un parqueadero. Encuentras cuatro comparables:</p>
<table>
<thead><tr><th>Comparable</th><th>Precio</th><th>Área</th><th>$/m² bruto</th><th>Ajustes</th><th>$/m² ajustado</th></tr></thead>
<tbody>
<tr><td>A · Mismo edificio, piso 2, sin vista, vendido hace 4 meses</td><td>$480 M</td><td>82 m²</td><td>$5,85 M</td><td>+4 % por piso y vista</td><td>$6,09 M</td></tr>
<tr><td>B · Edificio vecino, 8 años, remodelado, en oferta</td><td>$560 M</td><td>78 m²</td><td>$7,18 M</td><td>−6 % por antigüedad y acabados; −5 % por ser oferta</td><td>$6,39 M</td></tr>
<tr><td>C · Misma manzana, 20 años, sin parqueadero, vendido hace 2 meses</td><td>$430 M</td><td>79 m²</td><td>$5,44 M</td><td>+8 % por parqueadero; +3 % por antigüedad</td><td>$6,04 M</td></tr>
<tr><td>D · Conjunto cercano, 3 años, piscina, en oferta</td><td>$690 M</td><td>85 m²</td><td>$8,12 M</td><td>Descartado: supera el ±15 % de ajuste</td><td>—</td></tr>
</tbody>
</table>
<p>Con A, B y C el valor ajustado se mueve entre 6,04 y 6,39 millones por metro cuadrado, una dispersión aceptable. La media, 6,17 millones, multiplicada por 80 m² da un valor comercial probable cercano a <strong>494 millones</strong>, con un rango razonable entre 483 y 511. El comparable D, el que suele citar el vecino, no sirve: es otro producto. Fíjate también en que el único comparable realmente parecido, el A, se firmó por 480. Ese dato vale más que cualquier aviso.</p>
<aside class="nota"><p>Cuando pidas un estudio de mercado, pide ver los comparables, uno por uno, con su fuente y sus ajustes. Si no te los muestran, no es un estudio: es una opinión.</p></aside>

<h2>4. Lo que mueve el precio, con evidencia</h2>
<p>Los ajustes del paso tres no son al gusto. Hay investigación, parte de ella del propio Banco de la República, que mide cuánto pesa cada atributo en Bogotá. Conviene conocerla para que nadie te venda humo en ninguna dirección.</p>
<h3>Estrato</h3>
<p>Es el factor de mayor peso en Bogotá, por encima de casi cualquier característica física. Un modelo hedónico del Banco de la República con vivienda nueva en Bogotá encontró que, tomando el estrato 5 como base, el estrato 6 vale entre 21 y 36 % más, el estrato 4 entre 13 y 19 % menos y el estrato 3 entre 44 y 49 % menos (<a href="https://repositorio.banrep.gov.co/bitstreams/8464112f-74a8-4c42-8ece-fedb3ec3bda9/download" title="Banco de la República, Borrador de Economía 1072 (2019), anexo 1: modelo hedónico para Bogotá">Borrador 1072, 2019</a>). El mismo estudio estima que cada metro cuadrado adicional sube el precio entre 0,8 y 1,1 %. En precios de oferta, Properati midió que el metro cuadrado de los estratos 5 y 6 ($6,86 millones) era hasta 40,5 % más caro que el de los estratos 3 y 4 ($4,88 millones) a mediados de 2024 (<a href="https://www.portafolio.co/mis-finanzas/vivienda/precio-del-metro-cuadrado-en-estratos-altos-en-bogota-es-hasta-40-mas-caro-que-en-estrato-medio-613608" title="Portafolio, 18 de septiembre de 2024, con datos de Properati">Portafolio</a>). Por eso comparar tu apartamento con uno de otro estrato, aunque esté a tres cuadras, es el primer error.</p>
<h3>Parqueadero</h3>
<p>Un estudio hedónico espacial sobre Bogotá encontró que cada garaje adicional eleva el precio por metro cuadrado de forma estadísticamente significativa (<a href="https://dialnet.unirioja.es/descarga/articulo/4833905.pdf" title="Perdomo, Lecturas de Economía n.º 73 (2010): modelo hedónico espacial para Bogotá">Perdomo, 2010</a>). En zonas donde el parqueadero escasea, como Chapinero o algunos sectores de Suba, el efecto es mayor que en conjuntos nuevos donde todos tienen uno.</p>
<h3>Transporte: TransMilenio y Metro</h3>
<p>Estar cerca de una estación suma, pero menos de lo que se cree y solo hasta cierta distancia. Un estudio publicado en 2025 en Cuadernos de Geografía de la Universidad Nacional midió un efecto máximo de +8,4 % junto a la estación de TransMilenio, que se diluye a cero a 500 metros, con un promedio de +3 % (<a href="https://revistas.unal.edu.co/index.php/rcg/article/view/104098" title="Arenas Castro, Cuadernos de Geografía, Universidad Nacional, 2025">Arenas Castro, 2025</a>). La Secretaría Distrital de Planeación encontró que el anuncio de la troncal de la Avenida 68 subió el precio de las casas entre 8,6 y 14,1 % según la distancia, pero no tuvo efecto significativo en apartamentos (<a href="https://sistemas002.sdp.gov.co/sites/default/files/precios_de_la_vivienda_y_accesibilidad.pdf" title="Secretaría Distrital de Planeación, noviembre de 2021: precios de la vivienda y accesibilidad">SDP, 2021</a>).</p>
<p>Con el Metro la historia es más potente. Un estudio de la Universidad de los Andes y ProBogotá, con apoyo del Lincoln Institute, calculó que el suelo residencial a menos de 800 metros de las estaciones de la Primera Línea se valorizó 11,7 % tras el anuncio y 8,8 % adicional durante la obra (<a href="https://www.valoraanalitik.com/metro-de-bogota-puso-a-ganar-dinero-a-ciudadanos-suelo-tuvo-importante-valorizacion/" title="Valora Analitik, 20 de febrero de 2026, sobre el estudio Bogotank (Uniandes y ProBogotá)">Valora Analitik, febrero de 2026</a>). Pero ojo: no es parejo. Properati comparó 60 barrios junto a la Primera Línea y encontró que 39 subieron y 21 bajaron entre 2023 y 2024 (<a href="https://www.portafolio.co/mis-finanzas/vivienda/obras-del-metro-de-bogota-estan-generando-valorizacion-de-viviendas-611757" title="Portafolio, 23 de agosto de 2024, con datos de Properati">Portafolio</a>). Si tu apartamento está en zona de obra, hoy puede valer menos de lo que valdrá en 2028, y eso cambia la decisión de cuándo vender.</p>
<h3>Piso, antigüedad, vista, ascensor y administración</h3>
<p>Aquí toca ser honestos: para Bogotá no existe un estudio público que ponga un porcentaje confiable a la vista exterior o al ascensor. El estudio de Perdomo encontró que el piso suma y la antigüedad resta, con el signo esperado, pero sin significancia estadística en su muestra (<a href="https://dialnet.unirioja.es/descarga/articulo/4833905.pdf" title="Perdomo, 2010: coeficientes de piso y antigüedad">Perdomo, 2010</a>). Lo que sí sabemos por la práctica diaria es lo que hace un comprador: descuenta mentalmente la cuota de administración (una de 600.000 pesos frente a una de 300.000 es, a diez años, una diferencia de 36 millones), penaliza los pisos bajos sin ascensor y paga más por la luz y la vista. En un ACM esos ajustes se hacen con criterio y comparables locales, no con tablas universales.</p>
<p>Un dato que sí está medido: las cuotas de administración subieron con fuerza en 2026 por el ajuste del salario mínimo, con alzas proyectadas de entre 20 y 25 % (<a href="https://www.ciencuadras.com/blog/wp-content/uploads/2026/03/Informe-inmobiliario-2025.pdf" title="Ciencuadras, Informe inmobiliario 2025 (marzo de 2026)">Ciencuadras, 2026</a>). Un comprador informado lo tiene en cuenta.</p>

<h2>5. Cuánto se está pidiendo hoy</h2>
<p>Los precios por metro cuadrado que circulan en portales son precios de <em>oferta</em>, no de cierre. Sirven para ubicarte, no para fijar tu precio. Con esa advertencia, estos son los más recientes para Bogotá.</p>
<table>
<thead><tr><th>Localidad</th><th>$/m² apartamento en venta (oferta, I trim. 2026)</th></tr></thead>
<tbody>
<tr><td>Chapinero</td><td>$9.068.935</td></tr>
<tr><td>Usaquén</td><td>$7.382.727</td></tr>
<tr><td>Suba</td><td>$6.410.341</td></tr>
<tr><td>Engativá</td><td>$5.270.544</td></tr>
<tr><td>Kennedy</td><td>$5.160.855</td></tr>
<tr><td><strong>Promedio Bogotá (nueva y usada)</strong></td><td><strong>$7.421.952</strong></td></tr>
</tbody>
</table>
<p>Fuente: <a href="https://www.ciencuadras.com/blog/evolucion-del-mercado-de-vivienda/novedades-mercado-inmobiliario-bogota-2026/amp" title="Ciencuadras, 27 de mayo de 2026: novedades del mercado inmobiliario en Bogotá, I trimestre de 2026">Ciencuadras, I trimestre de 2026</a>. Para el segundo trimestre, el mismo portal ubicó el apartamento <strong>usado</strong> en Bogotá en $5.971.872 por metro cuadrado y un precio promedio de 817 millones (<a href="https://www.ciencuadras.com/blog/wp-content/uploads/2026/08/Informe-I-semestre-2026.pdf" title="Ciencuadras, Informe del primer semestre de 2026">Informe I semestre 2026</a>). En vivienda nueva, Tinsa calculó un promedio de 5.028.000 pesos por metro cuadrado en 2025, con el segmento premium de estrato 6 entre 12 y 16 millones (<a href="https://vivienda.com.co/bogota-medellin-precio-metro-cuadrado-miami-2026/" title="Vivienda.com.co, 1 de marzo de 2026, citando a Tinsa">vivienda.com.co</a>). Y en los barrios de mayor valor, el estudio de la Lonja de Bogotá para propiedad horizontal registró La Cabrera en 12,9 millones por metro cuadrado para edificios de hasta diez años y en 8,8 millones para los de más de treinta (<a href="https://www.metrocuadrado.com/noticias/actualidad/valor-del-metro-cuadrado-por-barrio-en-bogota-6020" title="Metrocuadrado, con datos del Estudio de Valores PH de la Lonja de Bogotá">Metrocuadrado</a>).</p>
<p>Mira la diferencia entre el promedio general ($7,4 millones) y el de vivienda usada ($5,97 millones): es la brecha entre lo nuevo y lo usado dentro de la misma ciudad. Si tu apartamento tiene 15 años y lo comparas con el promedio de la localidad, te vas a equivocar hacia arriba.</p>
<aside class="nota"><p>El promedio de una localidad esconde barrios que valen el doble unos de otros. Suba incluye Colina Campestre y también sectores de estrato 2. Un comparable útil está en tu barrio, en tu estrato y en tu rango de antigüedad; no en tu localidad.</p></aside>

<h2>6. Precio de publicación y precio de cierre</h2>
<p>Esta es la sección que ninguna plataforma te muestra, porque los portales conocen el precio al que publicaste y no el precio al que firmaste. En Colombia no hay un estudio público que mida el descuento promedio entre aviso y escritura, y desconfía de quien te dé una cifra redonda como si lo hubiera.</p>
<p>Lo que sí está medido es la distancia entre lo que piden los vendedores y lo que buscan los compradores. Properati cruzó ambos en 2024 y encontró que en <strong>85 de las 98 UPZ</strong> de Bogotá el precio que buscan los compradores está por debajo del que piden los vendedores, con brechas de hasta 35,8 % en Gran Yomasa y 34,4 % en Ciudad Montes (<a href="https://www.portafolio.co/mis-finanzas/vivienda/cuanto-estan-dispuestos-los-bogotanos-a-pagar-por-un-apartamento-609649" title="Portafolio, 26 de julio de 2024, con datos de Properati">Portafolio, julio de 2024</a>). Esa brecha es la que explica los tiempos de venta.</p>
<p>Y los tiempos son largos. Fincaraíz calcula que una vivienda usada tarda entre cuatro y siete meses desde que se publica hasta que se vende (<a href="https://www.valoraanalitik.com/bogota-medellin-cali-oferta-vivienda-usada/" title="Valora Analitik, 19 de septiembre de 2025, con datos de Fincaraíz">Valora Analitik, septiembre de 2025</a>). Asobancaria midió 8,9 meses para los estratos 4 a 6 a nivel nacional, frente a 4,8 meses una década antes (<a href="https://vivienda.com.co/?p=904" title="Vivienda.com.co, 11 de septiembre de 2025, con datos de Asobancaria">vivienda.com.co</a>). Un estudio de Habi con Synapsis encontró que cerca del 40 % de los vendedores tarda más de siete meses (<a href="https://www.portafolio.co/mis-finanzas/vivienda/ventas-de-vivienda-en-colombia-se-demoran-hasta-siete-anos-en-realizarse-segun-estudio-590832" title="Portafolio, octubre de 2023, sobre el estudio de Habi y Synapsis">Portafolio</a>). En Bogotá hay 37.680 inmuebles usados en oferta solo en Fincaraíz, con la mayor concentración en Colina Campestre, Cedritos, Santa Bárbara y Engativá (<a href="https://www.valoraanalitik.com/bogota-medellin-cali-oferta-vivienda-usada/" title="Valora Analitik, septiembre de 2025">misma fuente</a>). Es decir: tu apartamento compite con miles, y muchos de ellos en tu misma zona.</p>
<p>El contexto de 2026 lo hace más difícil para quien sale con el precio equivocado. En el primer semestre, los desistimientos de compra de vivienda nueva en Bogotá crecieron 32,1 % y llegaron al 28,5 % de las ventas (<a href="https://observatorio.habitatbogota.gov.co/wp-content/uploads/2026/07/MV_Junio_2026.pdf" title="Observatorio del Hábitat de Bogotá, boletín de mercado de vivienda, junio de 2026, con datos de Camacol">Observatorio del Hábitat, junio de 2026</a>): la gente firma y luego no consigue el crédito. Con tasas hipotecarias cercanas al 15 % y la tasa del Banco de la República en 12,25 %, el comprador que llega tiene menos capacidad y más opciones. Un precio defendible con comparables es lo único que lo retiene.</p>
<p>Hay una paradoja que juega a tu favor: la oferta de vivienda nueva No VIS cayó y, según Ciencuadras, cerca del 70 % de la demanda se orienta hacia la vivienda usada por la entrega inmediata (<a href="https://www.ciencuadras.com/blog/?p=130579" title="Ciencuadras, 24 de marzo de 2026">Ciencuadras, marzo de 2026</a>). Hay compradores. Lo que no hay es paciencia para precios de fantasía.</p>

<h2>7. El atajo del arriendo</h2>
<p>Hay una prueba de cordura que puedes hacer en un minuto. La Ley 820 de 2003 dice que el canon mensual de un arriendo de vivienda «no podrá exceder el uno por ciento (1 %) del valor comercial del inmueble» (<a href="http://www.secretariasenado.gov.co/senado/basedoc/ley_0820_2003.html" title="Ley 820 de 2003, artículo 18: renta de arrendamiento">artículo 18</a>). Dale la vuelta: si apartamentos como el tuyo se arriendan en 2,5 millones en tu edificio o en tu cuadra, el valor comercial que sostiene ese canon es de al menos 250 millones. No es un avalúo ni sustituye el método de comparación; es una vara para detectar precios absurdos. Si pides 600 millones por un apartamento que se arrienda en 2 millones, el mercado te está diciendo algo.</p>
<p>En sentido inverso, el método de renta o capitalización por ingresos que reconoce el Decreto 1420 (<a href="https://www.ani.gov.co/sites/default/files/decreto_1420_de_1998_tema_avaluos.pdf" title="Decreto 1420 de 1998, artículo 25">artículo 25</a>) es el que usan los inversionistas: miran la rentabilidad del arriendo frente a lo que paga un CDT. Con tasas de referencia en 12,25 %, un inversionista exige rentabilidades que muchos precios de oferta no entregan. Si tu comprador probable es inversionista, esa es la cuenta que va a hacer.</p>

<h2>8. Antes de publicar</h2>
<p>Lo que hagas antes de poner el aviso determina a cuánto vendes. Esta lista resume lo que revisamos nosotros antes de aceptar un inmueble, y sirve igual si decides vender por tu cuenta.</p>
<ul>
<li><strong>Certificado de tradición y libertad reciente.</strong> Confirma que no hay hipoteca sin cancelar, embargo, patrimonio de familia o afectación a vivienda familiar que exija firmas adicionales. Un comprador con crédito lo va a pedir y cualquier sorpresa aquí cuesta semanas.</li>
<li><strong>Paz y salvos de administración y predial.</strong> Sin ellos no hay escritura. Si debes cuotas, descuéntalas desde ya de tu cuenta.</li>
<li><strong>Tres cierres reales, no tres avisos.</strong> Pregunta en el edificio, a la administración, a vecinos que vendieron. Un solo cierre reciente en tu mismo edificio vale más que diez avisos de la zona.</li>
<li><strong>Tu precio en tres números.</strong> Mínimo aceptable, valor probable y precio de salida. Si el de salida queda más de 5 a 7 % por encima del probable, estás pagando con meses.</li>
<li><strong>Las primeras tres fotos.</strong> Son las que decide el comprador en segundos. Luz natural, espacios despejados, sin personas ni objetos personales. Una foto oscura del baño en la primera posición cuesta visitas.</li>
<li><strong>Un filtro para los contactos.</strong> Cincuenta mensajes no son cincuenta compradores. Antes de cada visita, pregunta presupuesto, forma de pago y plazo. Quien no responde a eso no va a ofertar.</li>
<li><strong>Un plan para las primeras cuatro semanas.</strong> Es cuando el aviso recibe más atención. Si en ese tiempo hay visitas y ninguna oferta, el problema suele ser el precio; si no hay visitas, suele ser la presentación o la publicación.</li>
</ul>
<aside class="nota"><p>Bajar el precio después de cuatro meses publicado no recupera el impulso de las primeras semanas: los compradores que buscan en tu zona ya vieron tu aviso y lo descartaron. Por eso el precio de salida importa más que cualquier rebaja posterior.</p></aside>

<h2>9. Cuánto te queda</h2>
<p>Saber cuánto vale no es saber cuánto recibes. Entre el precio de venta y tu cuenta bancaria hay al menos cuatro descuentos: la comisión de la inmobiliaria, tu mitad de los gastos de notaría, la retención en la fuente del 1 % que practica el notario cuando el vendedor es persona natural (<a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr016.html" title="Estatuto Tributario, artículo 398: retención en la enajenación de activos fijos de personas naturales">Estatuto Tributario, artículo 398</a>) y, si lo tuviste dos años o más, el impuesto de ganancia ocasional del 15 % sobre la utilidad (<a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr012.html" title="Estatuto Tributario, artículo 300: utilidad en la enajenación de activos fijos poseídos dos años o más">artículos 300</a> y <a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr013.html" title="Estatuto Tributario, artículo 314: tarifa de ganancia ocasional para personas naturales residentes">314</a>). Si es tu vivienda de habitación y el dinero va a una cuenta AFC, a otra vivienda o a pagar la hipoteca, las primeras 5.000 UVT de utilidad están exentas (<a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr013.html" title="Estatuto Tributario, artículo 311-1, modificado por la Ley 2277 de 2022">artículo 311-1</a>). Lo puedes calcular con tus cifras en la <a href="https://www.lomazhome.com/calculadora.html#neto" title="Calculadora ¿Cuánto te queda? de LoMaz Home">calculadora «¿Cuánto te queda?»</a>.</p>

<h2>Preguntas frecuentes</h2>
<p><strong>¿Puedo usar el avalúo catastral para fijar el precio?</strong><br>No. Es un valor fiscal, calculado en masa, que por norma puede estar entre el 60 y el 100 % del comercial. Sirve para saber que no estás por debajo de él, nada más.</p>
<p><strong>¿Necesito un avalúo comercial para vender?</strong><br>No es obligatorio. Lo pedirá el banco de tu comprador si hay crédito, y conviene tenerlo en sucesiones, divorcios o ventas entre familiares. Para fijar el precio de salida, un estudio de mercado bien hecho cumple la misma función.</p>
<p><strong>¿Qué es exactamente un ACM?</strong><br>Un análisis comparativo de mercado: la aplicación del método de comparación a tu inmueble, con comparables identificados, ajustados y una conclusión en rango. No tiene valor legal, pero es la herramienta con la que una inmobiliaria seria decide el precio.</p>
<p><strong>Mi vecino vendió más caro, ¿por qué el mío vale menos?</strong><br>Primero confirma que vendió, y a cuánto: los avisos dicen una cosa y las escrituras otra. Si de verdad vendió más caro, revisa piso, vista, parqueadero, estado y fecha. En un mercado que sube 7 % al año, seis meses de diferencia cambian el número.</p>
<p><strong>¿Es mejor publicar alto y bajar después?</strong><br>Es la estrategia más común y la más costosa. Las primeras semanas concentran la atención de los compradores activos; un precio alto los pierde y las rebajas posteriores los recuperan solo en parte. Es mejor salir dentro del rango probable con margen de negociación.</p>
<p><strong>¿Cuánto tarda en venderse un apartamento en Bogotá?</strong><br>Entre cuatro y siete meses según Fincaraíz; cerca de nueve en estratos altos según Asobancaria. Con un precio bien puesto y una presentación cuidada, las ventas que cerramos en el norte de Bogotá han tomado bastante menos; con precio equivocado, cualquier inmueble puede pasar un año publicado.</p>

<div class="cta"><p>En LoMaz Home, la correduría independiente de vivienda y locales comerciales que fundó Salomón Mazabell Torres Barrera en Bogotá, no publicamos y esperamos: medimos, presentamos, atraemos, filtramos y negociamos. Si quieres saber si el problema de tu inmueble es el precio, la presentación o la demanda, pide el <a href="https://www.lomazhome.com/vender.html" title="Diagnóstico LO MÁS de venta">Diagnóstico LO MÁS</a>: 20 minutos, sin costo y sin compromiso.</p></div>

<h2>Fuentes</h2>
<ul>
<li>DANE, Índice de Precios de la Propiedad Residencial, I trimestre de 2026, vía <a href="https://www.portafolio.co/mis-finanzas/vivienda/la-vivienda-esta-un-7-09-mas-cara-en-bogota-su-mayor-alza-en-cinco-trimestres-pese-a-la-baja-de-tasas-del-banrep-496289">Portafolio</a>.</li>
<li>DANE, Boletín técnico IPVN, II trimestre de 2026: <a href="https://www.dane.gov.co/files/operaciones/IPVN/bol-IPVN-IItrim2026.pdf">dane.gov.co</a>.</li>
<li>Alcaldía de Bogotá, censo inmobiliario 2026: <a href="https://bogota.gov.co/mi-ciudad/hacienda/bogota-alcanza-945-billones-en-valor-catastral-y-crece-29-en-2026">bogota.gov.co</a>; Catastro Bogotá, <a href="https://www.catastrobogota.gov.co/pregunta/que-es-el-avaluo-catastral">¿qué es el avalúo catastral?</a></li>
<li>Decreto 1420 de 1998 (<a href="https://www.ani.gov.co/sites/default/files/decreto_1420_de_1998_tema_avaluos.pdf">texto</a>); Resolución 620 de 2008 del IGAC (<a href="https://www.alcaldiabogota.gov.co/sisjur/normas/Norma1.jsp?i=36158">texto</a>); Ley 1673 de 2013 (<a href="http://www.secretariasenado.gov.co/senado/basedoc/ley_1673_2013.html">texto</a>); Registro Abierto de Avaluadores (<a href="https://www.raa.org.co/">raa.org.co</a>); Ley 820 de 2003 (<a href="http://www.secretariasenado.gov.co/senado/basedoc/ley_0820_2003.html">texto</a>).</li>
<li>Banco de la República, Borrador de Economía 1072 (2019): <a href="https://repositorio.banrep.gov.co/bitstreams/8464112f-74a8-4c42-8ece-fedb3ec3bda9/download">repositorio</a>.</li>
<li>Perdomo, J. A., «Una propuesta metodológica para estimar los cambios sobre el valor de la propiedad», Lecturas de Economía n.º 73 (2010): <a href="https://dialnet.unirioja.es/descarga/articulo/4833905.pdf">Dialnet</a>.</li>
<li>Arenas Castro, Cuadernos de Geografía, Universidad Nacional (2025): <a href="https://revistas.unal.edu.co/index.php/rcg/article/view/104098">revistas.unal.edu.co</a>; Secretaría Distrital de Planeación (2021): <a href="https://sistemas002.sdp.gov.co/sites/default/files/precios_de_la_vivienda_y_accesibilidad.pdf">documento</a>.</li>
<li>Estudio Bogotank (Universidad de los Andes y ProBogotá) sobre el Metro, vía <a href="https://www.valoraanalitik.com/metro-de-bogota-puso-a-ganar-dinero-a-ciudadanos-suelo-tuvo-importante-valorizacion/">Valora Analitik</a>; Properati sobre barrios de la Primera Línea, vía <a href="https://www.portafolio.co/mis-finanzas/vivienda/obras-del-metro-de-bogota-estan-generando-valorizacion-de-viviendas-611757">Portafolio</a>.</li>
<li>Ciencuadras: <a href="https://www.ciencuadras.com/blog/evolucion-del-mercado-de-vivienda/novedades-mercado-inmobiliario-bogota-2026/amp">I trimestre de 2026</a>, <a href="https://www.ciencuadras.com/blog/wp-content/uploads/2026/08/Informe-I-semestre-2026.pdf">Informe I semestre de 2026</a>, <a href="https://www.ciencuadras.com/blog/wp-content/uploads/2026/03/Informe-inmobiliario-2025.pdf">Informe inmobiliario 2025</a>; Tinsa vía <a href="https://vivienda.com.co/bogota-medellin-precio-metro-cuadrado-miami-2026/">vivienda.com.co</a>; Lonja de Bogotá vía <a href="https://www.metrocuadrado.com/noticias/actualidad/valor-del-metro-cuadrado-por-barrio-en-bogota-6020">Metrocuadrado</a>; Properati vía <a href="https://www.portafolio.co/mis-finanzas/vivienda/precio-del-metro-cuadrado-en-estratos-altos-en-bogota-es-hasta-40-mas-caro-que-en-estrato-medio-613608">Portafolio</a> y <a href="https://www.portafolio.co/mis-finanzas/vivienda/cuanto-estan-dispuestos-los-bogotanos-a-pagar-por-un-apartamento-609649">Portafolio</a>.</li>
<li>Tiempos de venta: Fincaraíz vía <a href="https://www.valoraanalitik.com/bogota-medellin-cali-oferta-vivienda-usada/">Valora Analitik</a>; Asobancaria vía <a href="https://vivienda.com.co/?p=904">vivienda.com.co</a>; Habi y Synapsis vía <a href="https://www.portafolio.co/mis-finanzas/vivienda/ventas-de-vivienda-en-colombia-se-demoran-hasta-siete-anos-en-realizarse-segun-estudio-590832">Portafolio</a>.</li>
<li>Observatorio del Hábitat de Bogotá, boletín de junio de 2026: <a href="https://observatorio.habitatbogota.gov.co/wp-content/uploads/2026/07/MV_Junio_2026.pdf">documento</a>; tasas: <a href="https://www.elpais.com.co/economia/credito-de-vivienda-en-colombia-estos-son-los-bancos-con-las-tasas-mas-bajas-en-septiembre-de-2026-1103.html">El País (Superfinanciera)</a> y <a href="https://www.elpais.com.co/economia/banco-de-la-republica-aumenta-su-tasa-de-interes-quedo-en-1225-3047.html">El País (Banco de la República)</a>.</li>
<li>Estatuto Tributario, artículos <a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr012.html">300</a>, <a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr013.html">311-1 y 314</a> y <a href="http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr016.html">398</a>.</li>
</ul>
$art$,
  null, 20, 'borrador',
  'b4839cd2-799d-4a60-8c8f-cb24f3b31cfa',
  coalesce((select nombre_completo from public.perfiles_usuarios where id = 'b4839cd2-799d-4a60-8c8f-cb24f3b31cfa'), 'LoMaz Home'),
  null
)
;
select id, slug, estado, autor_nombre, length(contenido) as caracteres from public.articulos_blog where slug = 'cuanto-vale-mi-apartamento-en-bogota';
